### PR TITLE
Update nextjs-aiding-hearts-dashboard

### PR DESCRIPTION
**Pull request by programmer12wc**
add this update

### CODE REVIEW

**Comment by programmer12wc** [comment]
hello good aftanoon plz add this

**Comment by programmer12wc** [comment]
update thi plz

**Comment by programmer12wc** [comment]
hello plz add this

**Comment by tffarhad** [comment]
Hi @programmer12wc,  Thank you for submitting the theme. You haven't followed the required format.
Please check out the [submission guide](https://github.com/statichunt/statichunt?tab=readme-ov-file#submit-a-theme), fix the issues, and resubmit. We'll add it. Thanks.

**Comment by programmer12wc** [comment]
hello
i make my all corrections plz add this

**Comment by programmer12wc** [comment]
Awesome, thanks for the update!

**Pull request merged**
