### PR TITLE
Create orion - construction website template nextjs

### PR DESCRIPTION
**Pull request by Robbythomas1992**

### CODE REVIEW

**Comment by Robbythomas1992** [comment]
Please approve my template and add this on your website.

**Comment by Robbythomas1992** [comment]
Please approve my template and add this on your website.

**Comment by Robbythomas1992** [comment]
Please publish product. its not showing on ststichunt.

**Comment by tffarhad** [comment]
Hi @Robbythomas1992,
The file structure wasn't followed, which caused it not to show up properly. I've fixed it. Please double-check the guidelines before submitting. Thanks a bunch for your contribution.

**Pull request merged**
